### ISSUE TITLE
Allow Custom Logrus

### ISSUE THREAD

**Issue by bscott** [meatballhat/negroni-logrus#10]
I can see a limitation when using the ```negronilogrus.NewCustomMiddleware``` Function as this does not allow for the use of custom hooks, example being https://github.com/rifflock/lfshook

https://github.com/meatballhat/negroni-logrus/blob/master/middleware.go#L27

**Comment by jszwedko** [comment]
@bscott this is true, though the struct field is public so you can do something like:

```go
    logger = logrus.New()
    logger.Formatter = new(logrus.JSONFormatter)
    logger.Hooks.Add(lfshook.NewHook(lfshook.PathMap{
        log.InfoLevel : "/var/log/info.log",
        log.ErrorLevel : "/var/log/error.log",
    }))

    middleware := negronilogrus.Middleware{
        Logger: logger,
        Name: "foo",
    }
```

I'll leave it to @meatballhat to decide if it's worth exposing that functionality through the API of `negronilogrus`, but I feel like it's a less used feature of `logrus` so requiring the struct initialization directly is fine for these cases where you need more control.

Thanks for raising the issue!

**Comment by bscott** [comment]
Thanks! @jszwedko 

So, here is what I did, but I'm trying to use the Logstash Formatter and running into issues, here is what I'm trying to do.

```
	logger := logrus.New()
	logger.Formatter = &logstash.LogstashFormatter
	logger.Hooks.Add(lfshook.NewHook(lfshook.PathMap{
		logrus.InfoLevel:  "logs/info.log",
		logrus.ErrorLevel: "logs/error.log",
	}))

	middleware := negronilogrus.Middleware{
		Logger: logger,
		Name:   "web",
	}

n := negroni.Classic()
n.Use(negronilogrus.New(middleware))
```

Errors:

```
undefined: negronilogrus.New
```

I understand that I can't use negronilogrus.New

**Comment by jszwedko** [comment]
@bscott once you have the middleware, you can just call `n.Use` with that, i.e.:

```
logger := logrus.New()
logger.Formatter = &logstash.LogstashFormatter
logger.Hooks.Add(lfshook.NewHook(lfshook.PathMap{
    logrus.InfoLevel:  "logs/info.log",
    logrus.ErrorLevel: "logs/error.log",
}))

middleware := negronilogrus.Middleware{
    Logger: logger,
    Name:   "web",
}

n := negroni.Classic()
n.Use(middleware)
```

**Comment by meatballhat** [comment]
@bscott is the current API sufficient for your needs? :smiley_cat:

**Comment by meatballhat** [comment]
@bscott bump ❤️ 

Closing soonish...

**Comment by jszwedko** [comment]
The soon is now. Please yell if you disagree though @bscott !
