### ISSUE TITLE
Should info message "started handling request" be optional?

### ISSUE THREAD

**Issue by petrkotek** [meatballhat/negroni-logrus#12]
Hi @meatballhat,

i wanted to hear your opinion about `entry.Info("started handling request")` ([see here](https://github.com/meatballhat/negroni-logrus/blob/master/middleware.go#L57)).

In a context of our service, it's not very helpful and we'd like to remove it (i.e. log only `"completed handling request"` info-message)

Q: Would you be ok with having functionality for suppressing the `started handling request` message?

Maybe there could be `func (l *Middleware) DisableRequestStartLogging()` or similar.

Let me know your opinion about this. I'm happy to prepare PR for that. Otherwise I'd need to use a fork in our service.

Thanks

**Comment by skyhighwings** [comment]
It would be neat to have a consolidated logging mode (i.e. httpd/nginx-style one line per request). I'm not sure if it fits the philosophy of this project, but it's worth thinking about.

**Comment by gravis** [comment]
I agree, a 1 liner log entry would be nicer.

**Comment by meatballhat** [comment]
I'm a fan of all the above :smiley_cat:.

**Comment by petrkotek** [comment]
:heart_eyes_cat: thanks, that's fantastic!
