### ISSUE TITLE
Error logging to logstash

### ISSUE THREAD

**Issue by smithrp** [meatballhat/negroni-logrus#19]
Hi @meatballhat ,

I'm trying to get logrus to log to our logstash servers, but it appears that with the latest version you cannot have "." in a field name anymore.  It also seems that all of the "completed handling request" messages have a field "measure#web.latency" in them which appears to be coming from line 119 of the middleware.go file.  Would it be a good idea to change that to "measure#%s**_**latency" instead?

Thanks in advance for the help!

**Comment by meatballhat** [comment]
@smithrp hey!  What do you think about a compromise of `"measure#%slatency"` with a default of `"web."`, then one could override with `"web_"` (or whatever else)?

**Comment by gravis** [comment]
We'll have to update our graylog accordingly (we have graphs based on that field).
Anyway, I'm wondering about the pertinence of this named latency. Could it be something else than just `latency`? I don't see any use-case where `latency` is not enough, maybe I'm wrong?

**Comment by meatballhat** [comment]
The reasoning for `measure#web.latency` is mostly I'm generally pro-namespace, the l2met examples use this form (https://github.com/ryandotsmith/l2met#l2met), and `web` is the heroku convention for the default HTTP dyno.

**Comment by smithrp** [comment]
@meatballhat  I'd be totally happy with the `"measure#%slatency"`.  Thanks for the quick reply!

**Comment by meatballhat** [comment]
@gravis how about `measure#%s` with default arg of `web.latency`, which would address both yours and @smithrp's concerns?

**Comment by smithrp** [comment]
@meatballhat Just to be _super_ clear, in my case I would then initialize the middleware with something like: `n.Use(negronilogrus.NewMiddlewareFromLogger(log, "web_latency"))` or I could keep the existing code of `n.Use(negronilogrus.NewMiddlewareFromLogger(log, "web"))` and would just get the `measure#web` as the field with latency?

**Comment by meatballhat** [comment]
@smithrp I'm not sure yet about the API.  I'd like to avoid changing the signature of `NewMiddlewareFromLogger`, and tbh I feel like this teensy library already has too much surface area.  What about supporting override of a func that only handles the [logrus entry formatting](https://github.com/meatballhat/negroni-logrus/blob/b8551f24ff84b857fd7ba43a2db4c0b97451249d/middleware.go#L115-L120)?

**Comment by smithrp** [comment]
@meatballhat Ultimate flexibility... I like it!

**Comment by gravis** [comment]
@meatballhat I think that's the way to go
Thanks! :)

**Comment by meatballhat** [comment]
@smithrp @gravis lmkwyt of #20 😁

**Comment by smithrp** [comment]
@meatballhat I'm still *extremely* new to Go but from my limited experience with it, your solution looks really good!  Thanks for the help and fast responses!
