### ISSUE TITLE
Support of urfave/negroni

### ISSUE THREAD

**Issue by sebastienfr** [meatballhat/negroni-logrus#22]
Hello,

Do you plan to support the codegansta/negroni migration to urfave/negroni ?

Regards.

**Comment by gravis** [comment]
yes, we should do that. 
It will be a breaking change, because even if it's the same project, the import path will be different, and go will probably refuse to compile existing projects.

**Comment by sebastienfr** [comment]
Yeah, that's the problem for all third party middlewares of negroni.
For the moment, I moved to https://github.com/zkilgore/negroni-logrus who did the job.

Doing a proper v2 would be nice. I'm not used to versioning Go dependencies but I mostly heard of http://labix.org/gopkg.in being a good solution. Hope it helps. Regards.

**Comment by jszwedko** [comment]
@sebastienfr thanks for the report! Closed in #23
