### ISSUE TITLE
Imports negroni from urfave instead of codegangsta

### ISSUE THREAD

**Issue by willfaught** [meatballhat/negroni-logrus#24]
https://github.com/meatballhat/negroni-logrus/blob/master/middleware.go#L10 breaks working with code that uses codegangsta/negroni:

    http: panic serving 172.17.0.1:34036: interface conversion: *negroni.responseWriterCloseNotifer is not negroni.ResponseWriter: missing method Before
    goroutine 10 [running]:
    net/http.(*conn).serve.func1(0xc420074980)
    	/somepath/go/1.7.4/libexec/src/net/http/server.go:1491 +0x12a
    panic(0x6950e0, 0xc420048cc0)
    	/somepath/go/1.7.4/libexec/src/runtime/panic.go:458 +0x243
    github.com/somepath/vendor/github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc420054b40, 0x7f519481e050, 0xc420024188, 0xc4200b61e0, 0xc4200b1500)
    	/somepath/src/github.com/bigcommerce/storefront/cmd/storefront/vendor/github.com/meatballhat/negroni-logrus/middleware.go:138 +0x363

codegangsta/negroni redirects to urfave/negroni. Can that be used instead?

**Comment by gravis** [comment]
You should try to `go get -u` in your project, this change is 5 months old :)
See 7c570a907cfc69cdc004ad506c6f5e234815b936

**Comment by willfaught** [comment]
I have the latest version, which is why I'm seeing the runtime failure. The
latest version uses the urfave import.

**Comment by gravis** [comment]
I'm sorry, I'm not following you.
You said "codegangsta/negroni redirects to urfave/negroni. Can that be
used instead?", I replied that's its already the case. Now you're
telling me that's the problem. So could  you tell me exactly what's
need to be done then?

I can see a "vendor" in the trace you posted, did you update that too?

**Comment by willfaught** [comment]
I'm sorry, let me clarify:

Since https://github.com/meatballhat/negroni-logrus/blob/master/middleware.go#L10 imports from urfave/negroni instead of codegangsta/negroni, your library won't work with code that uses codegangsta/negroni. The paths are textually different, so Go treats the packages as different; this is what caused the seemingly impossible error message above: "*negroni.responseWriterCloseNotifer is not negroni.ResponseWriter". The two "negroni" refer to different package paths.

Since codegangsta/negroni redirects to urfave/negroni, changing your code to import from codegangsta/negroni won't change how it works, but it will then be compatible with any other code that imports from codegangsta/negroni.

**Comment by gravis** [comment]
> changing your code to import from codegangsta/negroni won't change how it works, but it will then be compatible with any other code that imports from codegangsta/negroni.

and will be incompatible for everyone using urfave/negroni, for very same reason.

You have 2 options here:

- Update your code to use the new official urfave/negroni repo (strongly recommended)
- Vendor this lib with the commit https://github.com/meatballhat/negroni-logrus/commit/07babc99e899d3776e7b745d0b4c56680775136a
- Use your own fork

There's nothing more we can do on our side I'm afraid, unless @meatballhat sees another option?

**Comment by gravis** [comment]
Looks like a dup of urfave/negroni#159

**Comment by willfaught** [comment]
The conflict is with other third party libs. I'm afraid we'll have to do
option #4 then: drop this lib. Thanks for replying.

**Comment by jszwedko** [comment]
@willfaught out of curiosity, what are the other libraries that are depending on the old `github.com/codegangsta/negroni` path? This does expose a weakness in Go's import model (the ability to handle project renames), but we should at least reach out to them to update their references to avoid this confusion for future implementors.

Thanks for bringing this up!

**Comment by willfaught** [comment]
Just one dep it seems:

https://github.com/carbocation/interpose/blob/master/adaptors/negroni.go#L6

**Comment by gravis** [comment]
Thanks!
That's the same package as https://github.com/urfave/negroni/issues/159 then.
I'll try to create for PR interpose for that, hoping the project isn't dead (Latest commit 50c09d1  on Feb 15, 2015) :(

**Comment by gravis** [comment]
Interpose has been updated:
https://github.com/carbocation/interpose/pull/12#event-884361421
Can you please update your dep, and tell me if everything is ok now?
Thanks

**Comment by willfaught** [comment]
Works now! Thanks!

**Comment by gravis** [comment]
👍 :)
