### ISSUE TITLE
Logrus REPO change

### ISSUE THREAD

**Issue by djarbz** [meatballhat/negroni-logrus#34]
Compilation error
```
github.com\meatballhat\negroni-logrus\middleware.go:9:2: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"
```

Your import of Logrus should be github.com/Sirupsen/logrus

**Comment by jszwedko** [comment]
@djarbz is it possible that you have an old version of `logrus` in your $GOPATH`? They switched to lowercase a couple of years ago: https://github.com/sirupsen/logrus/pull/384

**Comment by djarbz** [comment]
@jszwedko I see that I do have the old version, not sure why though, I just recently downloaded it this year.
I was aware of the name change.
